### ISSUE TITLE
Feature Request: option to use .gitignore to ignore files that are not tracked by git

### ISSUE THREAD

**Issue by CruizeMissile** [jedmao/eclint#112]
I like this tool and find it very useful to keep my code clean and organized. I would like to see a way to ignore the files that are ignored by git. For example, I have third party projects in my repo that do not follow my .editorconfig file. I have ignored them in my .gitignore file so that changes in them will not be seen in my repo. When I run `eclint check *` in the root of my project, the submodule files are flagged as wrong. Yes, they are wrong but I don't care about them as it is not my code. This feature would be very nice.

**Comment by Kristinita** [comment]
@CruizeMissile , why you close this issue?

Thanks.
