### ISSUE TITLE
.gitignore paths starting with slash are not treated properly

### ISSUE THREAD

**Issue by bashmish** [jedmao/eclint#113]
In my .gitignore I have

```
/bower_components-1.x/
```

I want to exclude a folder on the root level, I'm sure this is a folder, and want to exclude it on the root level only, that's why I need slash both in the beginning and in the end.

`eclint` still checks this folder and complains about it.

If in `.gitignore` I do `bower_components-1.x/`, `eclint` skips it, but then in my project I have other dirs with this name excluded, for example `test/assets/bower_components-1.x/`, that I want to prevent.

Looks like a bug when processing exclusions starting with slash.

**Comment by gucong3000** [comment]
@bashmish Sorry for the late reply.

Maybe this will avoid the problem:

```shell
node eclint check $(git ls-files)
```
