### ISSUE TITLE
[Feature request] Is it possible to provide debug mode?

### ISSUE THREAD

**Issue by PeterDaveHello** [jedmao/eclint#123]
Hi @jedmao, thanks for writing such an awesome open source tool, it's very useful for me.

I just found that I'm facing a strange situation which may be caused by a bug of eclint, so I wonder how can I debug it.

I have my indent configured to 2 spaces, and I have some files with 4 indent but both `eclint check` & `eclint fix` do nothing on them, the result of `eclint infer` tells me the files are using 4-spaces indent which is correct, but it didn't detect anything wrong when I'm using `check` or `fix` command, do you have any suggestion, please?

Many thanks!

**Comment by PeterDaveHello** [comment]
This may be a bug from [editorconfig-core-js](https://github.com/editorconfig/editorconfig-core-js) as I use the command line of editorconfig nodejs version, it tells me that the files is using 2 spaces, but there is no 2 spaces indent in the files, so the infer of eclint is much more smarter than the upstream!

**Comment by gucong3000** [comment]
how can we get spaces number of one indent in a line? 8 spaces maybe 2, 4 or 8.

**Comment by PeterDaveHello** [comment]
I guess that's how the infer doing? 2 or 3 lines will help to decide the indent spaces?

**Comment by gucong3000** [comment]
`eclint` does not do syntax parsing, so we do not prevent users from using a two-unit indent.
If you want to parse syntax, you should use tools such as `gulp-stylelint`, `gulp-eslint`, etc.

**Comment by PeterDaveHello** [comment]
Yeah I guess so :)

**Comment by gucong3000** [comment]
Has your problem been resolved? Can I close this issue?
