### ISSUE TITLE
/* eslint-disable */  /* stylelint-disable */  not work 

### ISSUE THREAD

**Issue by pbwei** [jedmao/eclint#125]
eslint --color src && stylelint --color \"src/**/*.wxss\" && eclint check

eclint check 没有检查通过;

![image](https://user-images.githubusercontent.com/4220231/38141139-663029ae-3469-11e8-9d36-e82a2b04b272.png)

这个是使用第三方 代码；
已经使用 /* eslint-disable */  /* stylelint-disable */

**Comment by pbwei** [comment]
已经下载最新版本

**Comment by xuhdev** [comment]
Are you talking about [eslint](https://github.com/eslint/eslint/issues)? This is eclint. Your bug report is in the wrong place.

**Comment by gucong3000** [comment]
大哥你再怎么捣鼓空调遥控器，电视也关不掉的呀。
