### ISSUE TITLE
bug(update): npm WARN deprecated

### ISSUE THREAD

**Issue by Kristinita** [jedmao/eclint#126]
### 1. Summary

**If** I install eclint, I get warnings in console.

### 2. Environment

+ Operating systems:
    + Windows 10 Enterprise LTSB 64-bit EN (local),
    + Ubuntu 14.04.5 LTS (Travis CI).
+ Node.js 9.11.1,
+ npm 5.8.0,
+ eclint 2.6.0.

### 3. Steps to reproduce

    npm install -g eclint

### 4. Expected behavior

No warnings in console.

### 5. Actual behavior

[**See on Travis CI**](https://travis-ci.org/Kristinita/SashaTravis/jobs/365173753#L440-L442):

```bash
$ npm install -g eclint
npm WARN deprecated @types/commander@2.12.2: This is a stub types definition for commander (https://github.com/tj/commander.js). commander provides its own type definitions, so you don't need @types/commander installed!
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/home/travis/.nvm/versions/node/v9.11.1/bin/eclint -> /home/travis/.nvm/versions/node/v9.11.1/lib/node_modules/eclint/bin/eclint.js
+ eclint@2.6.0
added 286 packages in 13.368s
```

Thanks.

**Comment by gucong3000** [comment]
Upstream issues:
```bash
$ npm ls @types/commander
eclint@2.7.0 E:\work\eclint
`-- editorconfig@0.15.0
  `-- @types/commander@2.12.2

$ npm ls node-uuid
eclint@2.7.0 E:\work\eclint
`-- gulp-reporter@2.8.1
  `-- goo.gl@0.1.4
    `-- request@2.40.0
      `-- node-uuid@1.4.8
```
https://github.com/kaimallea/node-googl/issues/16
https://github.com/editorconfig/editorconfig-core-js/issues/65
