### ISSUE TITLE
feature_request(unicode): disable CROSS MARK symbol from output

### ISSUE THREAD

**Issue by Kristinita** [jedmao/eclint#129]
### 1. Summary

It would be nice, if [**CROSS MARK**](http://www.fileformat.info/info/unicode/char/274c/index.htm) symbol will not add to console output.

### 2. Argumentation

Different terminal behavior.

Compare line of output for [**Cygwin**](https://cygwin.com/) and [**ConEmu**](https://conemu.github.io/):

```markdown
Cygwin:

01:016 ❌ invalid newline: crlf, expected: lf (EditorConfig end_of_line https://goo.gl/te3t0s)

ConEmu:

01:016 ❌️ invalid newline: crlf, expected: lf (EditorConfig end_of_line https://goo.gl/te3t0s)
```

![Cygwin vs ConEmu](https://i.imgur.com/H54ps5S.png)

In ConEmu output I get [**VARIATION SELECTOR-16**](http://www.fileformat.info/info/unicode/char/fe0f/index.htm) symbol in each line.

It may create some problems in debugging process, examples:

1. User can have a different file size, if run same command in different operating systems/terminals. User may not understand the reasons.
1. File comparison tools show differences for each line.

### 3. Environment

+ Windows 10 Enterprise LTSB 64-bit EN,
+ Cygwin 2.10.0,
+ ConEmu 171205 [64],
+ eclint 2.6.0.

### 4. Example

For one of my big projects:

ConEmu:

    eclint check > SashaEClintWindows.txt 2>&1

`SashaEClintWindows.txt` — 1515 KB. Lines with `VARIATION SELECTOR-16`.

Cygwin:

    eclint check &> SashaEClintCygwin.txt

`SashaEClintCygwin.txt` — 1473 KB. Lines without `VARIATION SELECTOR-16`.

I get same output, but different file size because of `VARIATION SELECTOR-16` symbol.

Thanks.

**Comment by gucong3000** [comment]
Upstream issues：https://github.com/gucong3000/gulp-reporter/issues/237
