### ISSUE TITLE
eclint check parseable output format

### ISSUE THREAD

**Issue by guykisel** [jedmao/eclint#138]
Hey! eclint is awesome, thanks for building it. I was looking to wrap it with another tool, and something that a lot of linters provide is more easily parseable output such as json, yaml, or just simple lines that provide all the info you need (file path, line number, and error message) all in one line with a simple delimiter. The way eclint currently outputs its results to the console, you have to do _slightly_ more work to parse the output and track what file the messages refer to.

This is totally just a nice-to-have request.

**Comment by jedmao** [comment]
It already does what you want. You don't need to use the CLI.

**Comment by guykisel** [comment]
In this case I'm calling eclint from a python script, so the CLI is by far the easiest way to integrate with it.

**Comment by gucong3000** [comment]
`ECLint` supported JUnit and Checkstyle two kinds of XML file format outputs by `gulp-reporter`

**Comment by gucong3000** [comment]
@guykisel
Has your problem been resolved? Can I close this issue?

**Comment by guykisel** [comment]
if there are no plans to support more easily to parse output from the CLI then i'll close this. thanks.

**Comment by gucong3000** [comment]
It is work fine for me in `bash`:
```
$ env CI=True CIRCLECI=True eclint check 2> /dev/null || cat lint-reports/*/lint-result.xml

<testsuites>
  <testsuite name="E:\work\gulp-reporter\test\fixtures\csslint\invalid.css" tests="5" failures="0" errors="5" skipped="0">
    <testcase name="❌️ 无效的缩进风格：空格，预期：tab" classname="EditorConfig indent_style">
      <error message="E:\work\gulp-reporter\test\fixtures\csslint\invalid.css:3:1"/>
    </testcase>
    <testcase name="❌️ 无效的缩进风格：空格，预期：tab" classname="EditorConfig indent_style">
      <error message="E:\work\gulp-reporter\test\fixtures\csslint\invalid.css:4:1"/>
    </testcase>
    <testcase name="❌️ 无效的缩进风格：空格，预期：tab" classname="EditorConfig indent_style">
      <error message="E:\work\gulp-reporter\test\fixtures\csslint\invalid.css:9:1"/>
    </testcase>
    <testcase name="❌️ 无效的缩进风格：空格，预期：tab" classname="EditorConfig indent_style">
      <error message="E:\work\gulp-reporter\test\fixtures\csslint\invalid.css:10:1"/>
    </testcase>
    <testcase name="❌️ 无效的缩进风格：空格，预期：tab" classname="EditorConfig indent_style">
      <error message="E:\work\gulp-reporter\test\fixtures\csslint\invalid.css:11:1"/>
    </testcase>
  </testsuite>
```
