### ISSUE TITLE
eclint has reported vulnerabilities

### ISSUE THREAD

**Issue by ljharb** [jedmao/eclint#139]
`npm audit` reports tons of vulnerabilities via gulp-reporter (why is anything gulp-related a runtime dep?).

Can gulp-reporter (and all the gulp deps) be moved from deps to devDeps, since you only use it in tests?

**Comment by gucong3000** [comment]
> `npm audit` reports tons of vulnerabilities via gulp-reporter

Witch version of `eclint` you are using? I remember the problem was fixed.

> why is anything gulp-related a runtime dep?

`eclint` [is a gulp plugin](https://github.com/jedmao/eclint#gulp-plugin) but without name prefix `gulp-`

> Can gulp-reporter (and all the gulp deps) be moved from deps to devDeps,

It will use for CLI to show report to console.

**Comment by ljharb** [comment]
I'm using v2.7.0, and the issues are still reported by `npm audit`.

Gulp seems like a very heavyweight dependency just to output stuff to the console :-/

**Comment by gucong3000** [comment]
> I'm using v2.7.0, and the issues are still reported by npm audit.

Can you post report to here?

**Comment by gucong3000** [comment]
Gulp seems like a very heavyweight dependency

No. we just use `vinyl-fs` & `vinyl`

**Comment by ljharb** [comment]
hmm - i removed node_modules and then reinstalled and made a package-lock, and still saw the errors - but now when i try, the issues are indeed fixed. My apologies for the false positive!
