### ISSUE TITLE
A suggestion: for C projects, also optionally generates a .clang_complete file with C compiler flags

### ISSUE THREAD

**Issue by xuhdev** [jedmao/eclint#14]
[clang_complete](http://www.vim.org/scripts/script.php?script_id=3302) is an auto completion tool for C projects. It uses `.clang_complete` file as its configuration file. If one specifies:

    c_complete_flags = -I auto -D something

Do you think it's a good idea to generate a `.clang_complete` file at the root?

**Comment by jedmao** [comment]
Closing as not in the scope of this project.
