### ISSUE TITLE
`eclint fix *` does not fix the `max_line_length` rule violation

### ISSUE THREAD

**Issue by chenrui333** [jedmao/eclint#151]
I am trying to use `eclint fix` command to do the batch fix, unfortunately, I found I still saw the `eclint check` issue after applying the command. 

For example this file, https://github.com/chenrui333/website/blob/fix-editorconfig-style-issue/OWNERS_ALIASES

Firstly, I applied `eclint fix OWNERS_ALIASES`, silently passed. 
Then, I run `eclint check OWNERS_ALIASES`, it still throws bunch of errors:
```
$ eclint check OWNERS_ALIASES
OWNERS_ALIASES
    002:80 ❌ invalid line length: 97, exceeds: 80  (EditorConfig max_line_length https://goo.gl/DI51mx)
    008:80 ❌ invalid line length: 160, exceeds: 80 (EditorConfig max_line_length https://goo.gl/DI51mx)
    066:80 ❌ invalid line length: 86, exceeds: 80  (EditorConfig max_line_length https://goo.gl/DI51mx)
    088:80 ❌ invalid line length: 86, exceeds: 80  (EditorConfig max_line_length https://goo.gl/DI51mx)
    188:80 ❌ invalid line length: 88, exceeds: 80  (EditorConfig max_line_length https://goo.gl/DI51mx)
    197:80 ❌ invalid line length: 180, exceeds: 80 (EditorConfig max_line_length https://goo.gl/DI51mx)
    206:80 ❌ invalid line length: 98, exceeds: 80  (EditorConfig max_line_length https://goo.gl/DI51mx)
    216:80 ❌ invalid line length: 109, exceeds: 80 (EditorConfig max_line_length https://goo.gl/DI51mx)
```

Let me know if I want to do something special, thanks!

**Comment by jednano** [comment]
This tool [very intentionally does not "fix" `max_line_length` violations](https://github.com/jedmao/eclint/blob/adbeaddc3f25cd770f0b823a9f571585bb403e6c/lib/rules/max_line_length.ts#L28), as that would require knowledge of whatever language is contained within the file (AST).

**Comment by chenrui333** [comment]
I see, thanks for the code reference!

**Comment by chenrui333** [comment]
@jedmao looks like `indent_size` is noop too?
https://github.com/jedmao/eclint/blob/master/lib/rules/indent_size.ts#L73

**Comment by jednano** [comment]
Yes, because, again, it requires AST or knowledge of the language in question. I don't even believe in the concept behind this project any more for this very reason.
