### ISSUE TITLE
Please add support for end_of_line = native

### ISSUE THREAD

**Issue by dmitriyse** [jedmao/eclint#152]
See discussion here https://github.com/editorconfig/editorconfig/issues/226

```ini
end_of_line = native
```
should check LF on linux and CRLF on Windows.

**Comment by jednano** [comment]
https://github.com/editorconfig/editorconfig-vote/issues/2#issuecomment-343961234

**Comment by dmitriyse** [comment]
I have strong arguments for this feature. Unfortunately, editor config team has locked the issue, IMHO they have made a big mistake and loosed opportunity to listen to true feedback.  This feature was voted by a small number of people it cannot be a good decision for the project that is used by million developers.
Please do not do the same mistake. Please reopen it, to continue the discussion.

**Comment by nschonni** [comment]
Does `unset` not have the same affect? https://github.com/editorconfig/editorconfig-vote/issues/2#issuecomment-338457059

**Comment by dmitriyse** [comment]
NO! 
unsed = ignore
native = enforce (check or fix)

**Comment by dmitriyse** [comment]
For editors, it possible not so significant. But for plugins like eclink is a must. For example, you can commit CRLF to git repo under Linux and infect your repo with EOL hell.
eclink is a tool that helps to prevent that:
1) Check or fix CRLF on developer machine before commit
2) Check on CI

With "unset" you cannot do this.

**Comment by nschonni** [comment]
aside: the better solution for that if you're using Git, is to setup your .gitattributes file https://www.edwardthomson.com/blog/advent_day_21_renormalizing_line_endings.html

**Comment by dmitriyse** [comment]
https://github.com/editorconfig/editorconfig/issues/388

**Comment by dmitriyse** [comment]
Again "git renormalize" is a manual operation. How does it help to perform automated checks of every commit?
For example, an OpenSource Project should check every pull request for EOL infections on each build.

**Comment by dmitriyse** [comment]
You always suggesting to offload the "native EOL" check to git. Have the git ability to do all "fix and check"? The answer is no. 
eclint is a tool for that.  So you need to support "end_of_line = native" or parse .gitattributes.

Otherwise, EOL functionality of eclint is limited and does not cover the full reality of thousands of projects.

**Comment by dmitriyse** [comment]
Please reopen this feature, because at least the discussion is alive! And now we have an alive discussion in the editorconfig repo. (https://github.com/editorconfig/editorconfig/issues/388)

**Comment by nschonni** [comment]
> You always suggesting to offload the "native EOL" check to git. Have the git ability to do all "fix and check"? The answer is no.

It does, the steps are explained in the article I linked to with `git add --renormalize .`. Anyway, I don't think that ECLint should support something that EditorConfig doesn't, so I'm unsubscribing form this thread. Good luck

**Comment by dmitriyse** [comment]
@nschonni "git add --renormalize" couldn't help to automatically check problems in CI

**Comment by dmitriyse** [comment]
> so I'm unsubscribing form this thread.

It's not a polite form of discussion. 

@jedmao please reopen this issue.

I have demand on my OpenSource project to verify some files that correspond to logic "end_of_line = native"
Does not matter how it would be achieved "end_of_line = native" or "end_of_line = unset" or somehow else. 
eclint have already good infrastructure to do LF (On Linux) and CRLF (On Windows) checks for the choosen by mask files.
Pleaso do not force users to maintain their own "forks" with required functionality.

**Comment by jednano** [comment]
This is not the right place to discuss whether an EditorConfig rule should or should not be implemented. For the record, there's nothing stopping you from using `native` in your own implementations. EditorConfig works with any random value. This is all open source too, so you can fork any of these projects to your liking. You can continue the discussion on the EditorConfig issue tracker.
