### ISSUE TITLE
Publish on NPM

### ISSUE THREAD

**Issue by mcandre** [jedmao/eclint#19]
As a Node.js newbie, I want eclint published on [NPM](https://www.npmjs.com/), so that it's easy to install with `npm [-g] eclint`.

**Comment by jedmao** [comment]
Unfortunately, it doesn't even work yet and it never will because it's impossible to interpret a developer's intent when spaces are used for both indentation and alignment. http://jedmao.ghost.io/2014/08/20/tabs-vs-spaces-the-age-old-war/

**Comment by mcandre** [comment]
eclint could ignore that rule for now (even editorconfig doesn't support every rule in Google Style or Mozilla Style).

**Comment by jedmao** [comment]
I'm still trying to figure out the best strategy for that. Even still though, the rest of the rules aren't even complete yet. It's not an issue so much as it is an incomplete project.

**Comment by jedmao** [comment]
@mcandre you can look forward to a 0.1.0 release, probably later tonight. I just need to update the readme with all the necessary instructions. See [the milestones](https://github.com/jedmao/eclint/milestones).
