### ISSUE TITLE
indent size check is wrong

### ISSUE THREAD

**Issue by millermedeiros** [jedmao/eclint#24]
running `eclint check **/*.js` against the [esformatter](https://github.com/millermedeiros/esformatter/) repository, with setting:

```
[lib/**]
indent_style = space
indent_size = 2
```

it says:

```
lib/indent.js: line 69: invalid indent size: 5, expected: 2
lib/indent.js: line 70: invalid indent size: 5, expected: 2
lib/indent.js: line 71: invalid indent size: 5, expected: 2
```

source file: https://github.com/millermedeiros/esformatter/blob/b4dfb14a2ddaca8d1d5bc095f969f20c1114003a/lib/indent.js#L69-L71

**Comment by jedmao** [comment]
Thanks. I wrote a test to verify this bug. I'll get right on it.

**Comment by jedmao** [comment]
Fixed in https://github.com/jedmao/eclint/commit/0ed6d03d62d769b89a7dbc5a8af8cccfba82711a

**Comment by jedmao** [comment]
Published to npm in version 0.2.2

**Comment by jedmao** [comment]
@millermedeiros did that fix your issue?

**Comment by millermedeiros** [comment]
Yes it did! Thanks a lot
