### ISSUE TITLE
Allow final newlines to be removed on "fix"

### ISSUE THREAD

**Issue by treyhunner** [jedmao/eclint#25]
It looks like newlines are meant to be trimmed when fixing, but nothing seems to happen.

**Comment by jedmao** [comment]
They are, actually, but you probably haven't specified a destination folder to output the results. I know, it's not intuitive, but there appears to be no built-in way to do this with a gulp plugin and I haven't found anything promising. It's all [explained in the Readme](https://github.com/jedmao/eclint/blob/master/README.md#fix), which states:

> One difference you'll notice is an additional -d, --dest <folder> option. This option gives you control over where the result file tree will be written. It's not technically required, but if you don't specify this option then the files won't be written anywhere, which would be pointless. I'm still looking for a way to automatically overwrite the files provided in the <files>... args, which, when I do, this dest option will only be needed if you want to write the files elsewhere.

BTW – download the latest version. There was as issue with `undefined` being printed on the last line after removing final newlines (fixed).

**Comment by jedmao** [comment]
@treyhunner fixed in 6a4f84cc3642e3a7b37e9f9d7950ec2af55531de
