### ISSUE TITLE
fix does not fully fix all issues

### ISSUE THREAD

**Issue by lhoang29** [jedmao/eclint#35]
I'm applying eclint to this file here: https://github.com/eisber/vowpal_wabbit/blob/master/vowpalwabbit/gd.cc.

'check' showed some issues and 'fix' fixed some of them. Running 'check' again still shows there are more issues, but now 'fix' doesn't do anything to the file. Any ideas? The editorconfig file being used is here: https://github.com/eisber/vowpal_wabbit/blob/master/.editorconfig

I'm on Ubuntu 14.04, npm 1.4.28, node v0.10.40, installed eclint by 'sudo npm install -g eclint'

**Comment by jedmao** [comment]
You'll have to isolate the problem to be more specific about which issues are not being fixed.

**Comment by lhoang29** [comment]
Sure, here are the remaining issues. Doing fix after this does nothing.

vowpalwabbit/gd.cc: line 5: invalid indent size: 1, expected: 2
vowpalwabbit/gd.cc: line 157: invalid indent size: 11, expected: 2
vowpalwabbit/gd.cc: line 176: invalid indent size: 5, expected: 2
vowpalwabbit/gd.cc: line 177: invalid indent size: 3, expected: 2
vowpalwabbit/gd.cc: line 228: invalid indent size: 19, expected: 2
vowpalwabbit/gd.cc: line 325: invalid indent size: 1, expected: 2
vowpalwabbit/gd.cc: line 326: invalid indent size: 3, expected: 2
vowpalwabbit/gd.cc: line 327: invalid indent size: 3, expected: 2
vowpalwabbit/gd.cc: line 328: invalid indent size: 1, expected: 2
vowpalwabbit/gd.cc: line 330: invalid indent size: 1, expected: 2
vowpalwabbit/gd.cc: line 331: invalid indent size: 3, expected: 2
vowpalwabbit/gd.cc: line 332: invalid indent size: 1, expected: 2
vowpalwabbit/gd.cc: line 334: invalid indent size: 1, expected: 2
vowpalwabbit/gd.cc: line 335: invalid indent size: 1, expected: 2
vowpalwabbit/gd.cc: line 336: invalid indent size: 3, expected: 2
vowpalwabbit/gd.cc: line 337: invalid indent size: 3, expected: 2
vowpalwabbit/gd.cc: line 338: invalid indent size: 3, expected: 2
vowpalwabbit/gd.cc: line 339: invalid indent size: 1, expected: 2
vowpalwabbit/gd.cc: line 593: invalid indent size: 11, expected: 2
vowpalwabbit/gd.cc: line 597: invalid indent size: 11, expected: 2
vowpalwabbit/gd.cc: line 624: invalid indent size: 9, expected: 2
vowpalwabbit/gd.cc: line 625: invalid indent size: 3, expected: 2
vowpalwabbit/gd.cc: line 634: invalid indent size: 11, expected: 2
vowpalwabbit/gd.cc: line 638: invalid indent size: 11, expected: 2
vowpalwabbit/gd.cc: line 799: invalid indent size: 13, expected: 2
vowpalwabbit/gd.cc: line 810: invalid indent size: 17, expected: 2
vowpalwabbit/gd.cc: line 816: invalid indent size: 17, expected: 2
vowpalwabbit/gd.cc: line 861: invalid indent size: 11, expected: 2
vowpalwabbit/gd.cc: line 862: invalid indent size: 5, expected: 2
vowpalwabbit/gd.cc: line 998: invalid indent size: 3, expected: 2

**Comment by jedmao** [comment]
Ah, indent size. Of course! Indent size is a tricky thing to fix. In fact, I'm pretty sure it's impossible to fix w/o an AST parser for whatever language you're writing. As such, there's no way to fix this issue if you don't do it manually.

**Comment by lhoang29** [comment]
Ah. How do others deal with this? Perhaps a combination of eclint with some other language-specific tool (e.g. astyle)?

**Comment by jedmao** [comment]
The only way to "fix" indentation is to parse into AST and restyle it. EditorConfig isn't aware of your programming language at all, so "others" don't fix it in this context. If they do, I've never seen it, nor do I think it's possible. Even the AST fix destroys any whitespace for alignment you may have, so that's not perfect.

**Comment by lhoang29** [comment]
I understand, what I meant was to use a combination of eclint with another tool that can handle the language-specific structure. For instance, using eclint in the first round and astyle (http://astyle.sourceforge.net/) next to fix indent works for me. This isn't perfect, but I can leverage most of the editorconfig settings.

**Comment by jedmao** [comment]
That would be a viable solution! Closing.
