### ISSUE TITLE
gulp build does not work for me

### ISSUE THREAD

**Issue by nsedat** [jedmao/eclint#38]
building eclint stops with error 

> [16:39:21] Starting 'scripts'...
> **node_modules/linez/linez.d.ts(2,25): error TS2307: Cannot find module 'd.ts/linez'.**

steps before:

> git clone ...
> cd eclint
> npm install

_I'm doing anything wrong or forget something?_

FYI: I'll need to locally modify eclint to handle block-comments correctly for me  ... (these with leading space in front of "*" at 2nd line):

```
/**
 * description
 */
```

give error on check with settings

```
indent_style = tab
tab_width = 4
```

in .editorconfig

many thanks in advance

**Comment by gucong3000** [comment]
@nsedat fixed in master branch.
