### ISSUE TITLE
Correct indent_size setting to allow documentation comments

### ISSUE THREAD

**Issue by zakjan** [jedmao/eclint#39]
What is the correct setting to allow C-style block comments with documentation?

```
/**
 * ...
 */
```

eclint check with indent_size = 4 gives me many errors such as "invalid indent size: 5, expected: 4" on lines with one space more inside comments.

**Comment by jedmao** [comment]
There are no language specific settings in any editorconfig programs.

**Comment by jedmao** [comment]
See also https://github.com/jedmao/eclint/issues/37

**Comment by zakjan** [comment]
So it is unusable for projects with doc comments. Many languages use these. What can you recommend to me instead?

**Comment by jedmao** [comment]
Like I said, see #37. @denis-sokolov recommends [`lintspaces`](https://www.npmjs.com/package/lintspaces).

**Comment by zpbx** [comment]
@jedmao 
We really need this feature for documentation comments. Shall I make a PR for this?

**Comment by jedmao** [comment]
@zpbx, a PR will not be accepted for the same reasons stated above. EditorConfig shall not interpret language-specific syntax in any way. Please use lintspaces.

**Comment by zpbx** [comment]
I understand your opinion, you're right about EditorConfig's philosophy.

But this is a *linter* which is being used by developers in reality -- they write codes in language-specific syntaxes and they need this feature.

May I maintain a fork to implement this feature for myself?

**Comment by jedmao** [comment]
This is not just a linter, it's an EditorConfig linter, so it must align with the EditorConfig philosophy. If you want a language-specific linter, then use a language-specific linter, like ESLint for JavaScript. There's no reason you can't use 2 linters to achieve your goals. Just run eclint with the indentation rule turned off and you're good to go.

As for the fork, you can do whatever you want. This is all open source. You can link your fork to this thread if you want so others can find it. That's fine by me.

**Comment by zpbx** [comment]
I see. Thanks.

**Comment by zpbx** [comment]
Finally I use this option in `.editorconfig` to ignore indentation check for JS files.

```ini
[*]
indent_style = tab

[*.js]
indent_style =
```

It works fine with eclint.

**Comment by jedmao** [comment]
Yep. If it were me, I'd do `indent_style = ignore` just to add clarity.

**Comment by hax** [comment]
Though eclint may not add comment recognization builtin, but I think eclint should expose an configuration/api which let users config ignore pattern.

Example:
```sh
eclint --ignore-start "/**" --ignore-end "*/"
```
```js
eclint.check({ignore: { start: '/**', end: '*/' }})
```


Another option is just ignore one space follow non-whitespace in indent check. Because no one use one space as indent.

**Comment by jedmao** [comment]
@hax that configuration would be applied to all files, even ones that aren't written in the language in question. How do you propose to solve that problem?

**Comment by hax** [comment]
@jedmao I suggest just copy https://github.com/schorfES/node-lintspaces#ignores-option

**Comment by jedmao** [comment]
@hax this would still affect all files, regardless of language.

**Comment by hax** [comment]
I would like to say more about this issue:

In my opinion, disable `indent_style` due to not support doc comments is "lose a great deal through trying to save a little".
I'm considering change to some other tools which more practical in this problem. (eg. [lintspaces]( https://github.com/schorfES/node-lintspaces))

I strongly suggest reopen this issue.

**Comment by jedmao** [comment]
If lintspaces works for you then use it. I have no plans, personally, to implement this feature.

**Comment by gucong3000** [comment]
@zpbx 能给个联系方式么？我QQ64212001

**Comment by hax** [comment]
@gucong3000 I think the requirement is very clear as the comments from @zpbx and me, if you still need us to clarify something, just add comment and we will get notified.

**Comment by jedmao** [comment]
Reopening the issue in favor of mimicking the [lintspaces ignores option](https://github.com/schorfES/node-lintspaces#ignores-option). That's the best solution to this problem w/o introducing anything language-specific to the tool itself.

That said, I still have no plans to implement the feature myself, so I've added the "Accepting PRs" label.

**Comment by gucong3000** [comment]
LGM

**Comment by gucong3000** [comment]
Resolved in #62 
I think we need to describe this feature in the document. But I'm not good at english.
Can anybody help?

**Comment by jedmao** [comment]
You can write it in Chinese and my wife can help me translate it.

**Comment by gucong3000** [comment]
@jedmao 
Do you have a plan to release a new version?
So we can close this issue.

**Comment by jedmao** [comment]
If you're done making changes I can do a new release as soon as i have a minute.

**Comment by gucong3000** [comment]
@jedmao 
I am done making changes.

**Comment by schoetbi** [comment]
I came to the conclusion that formatting of C/C++ code should be done with an apropriate tool that also understands the semantic and is able to guarantee syntactic correctness. This is why I choose ClangFormat for my C/C++ files. See here: https://clang.llvm.org/docs/ClangFormat.html

Of course one can also use eclint for other file types.
