### ISSUE TITLE
Recursive path fails if no extension is provided

### ISSUE THREAD

**Issue by carlosasj** [jedmao/eclint#41]
I have a Django Project with all sort of files, and I want to check all my files especially for `end_of_line`.
If i run `eclint check **/*.html` so it find all my html files in all paths (no matter how depth it is), but I can't figure out how to check all files, without have to specify the extension.

For example:
- if I run `eclint check *` it only checks my root folder
- if i run `eclint check **/*` it only checks the files on "root" of each _child-folder_ BUT NOT on project folder.
- if i run `eclint check **/**/*` it only checks the files on "root" of each _child-child-folder_ BUT NOT on project folder nor on _child-folder_. (and so on)

Run things like `eclint check **/*.*` have same results as above. 

What am I doing wrong?

---------------

**.editorconfig**
```ini
# http://editorconfig.org

root = true

[*]
end_of_line = lf
insert_final_newline = true
charset = utf-8
trim_trailing_whitespace = true

[*.py]
indent_style = space
indent_size = 4

[*.{html,js}]
indent_style = tab

[*.{yml,scss}]
indent_style = space
indent_size = 2
```

```
$ eclint -v
1.1.5
```

```
$ npm -v
3.8.7
```

```
$ node -v
v5.11.0
```

**Comment by jedmao** [comment]
I think you want `eclint check **`. Does that work for you?

**Comment by carlosasj** [comment]
@jedmao I forgot to include that example:
if I run `eclint check **` it (also) only checks my root folder

**Comment by jedmao** [comment]
Well, eclint just uses glob syntax, so whatever works for that. Oh! You might want to try wrapping your globs in quotes though! `eclint check "**"`.

**Comment by carlosasj** [comment]
THAT'S IT!!!
I didn't tried with quotes, and it worked!!!
Thanks for your time! :smile:

**Comment by jedmao** [comment]
@carlosasj I'm curious. Are you running Bash on Windows? What's your OS? I have to use quotes on Windows, but I'm wondering about other operating systems.

**Comment by carlosasj** [comment]
No, I tried on Manjaro 15 and Ubuntu 15, both with same results (same fails with the tests of the first post, and with success with your last suggestion).
