### ISSUE TITLE
Error in comment

### ISSUE THREAD

**Issue by simonepri** [jedmao/eclint#44]
In javascript (and many others), this is a common way to declare some documentation for a certain piece of code:
```js
/**
 * Comment
 */
```
This exemple uses one space indentation, so if you set into your .editorconfig
indent_size = 2
and then you run eclint check on that exemple, it will give you this error:
`invalid indent size: 1, expected: 2`

I think it should be a way to ignore comments

**Comment by jedmao** [comment]
This very same issue has been reported before in https://github.com/jedmao/eclint/issues/39 and perhaps others.
