### ISSUE TITLE
Automatically run on all files in current directory

### ISSUE THREAD

**Issue by bfred-it** [jedmao/eclint#46]
I think eclint should automatically run on all non-binary non-vendor files is finds in the current directory

```sh
$ eclint check
```

should equal to something like

```sh
$ eclint check '**/*.*' '!node_modules/**/*.*'
```

coupled with #45 this would make eclint a config-free tool like [xo](https://github.com/sindresorhus/xo) for example

**Comment by gucong3000** [comment]
@bfred-it fixed in master branch.

**Comment by gucong3000** [comment]
should we release of a beta version first

**Comment by jedmao** [comment]
@gucong3000 I can't actually build master right now because https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14996 isn't yet published. Just waiting on that is all.
