### ISSUE TITLE
Ignore default node_modules directory

### ISSUE THREAD

**Issue by evilebottnawi** [jedmao/eclint#47]

**Comment by jedmao** [comment]
This should be requested on the main EditorConfig issue tracker.

https://github.com/editorconfig/editorconfig/issues

**Comment by evilebottnawi** [comment]
@jedmao nope, `eclint` written for javascript projects and only in their we have `node_modules`, it is not related to `EditorConfig` package.

**Comment by jedmao** [comment]
@evilebottnawi, yes, it is. You can use any EditorConfig core for any type of project. This means, in a JavaScript project with `node_modules`, you could be using the [C Core](https://github.com/editorconfig/editorconfig-core-c), not to mention a mixed project where you might have both Python files as well as JavaScript files, in which case you might use the [Python core](https://github.com/editorconfig/editorconfig-core-py) or [whatever suits you](https://github.com/editorconfig?q=core). Point is, a core feature like this belongs in all cores, not just one. If it were excluded to just the [JavaScript core](https://github.com/editorconfig/editorconfig-core-js) then it still wouldn't belong in this eclint project.
