### ISSUE TITLE
Beautiful console report

### ISSUE THREAD

**Issue by gucong3000** [jedmao/eclint#49]
I have a plugin named `gulp-reporter`
It was able to report errors found by gulp-eslint/gulp-jscs/gulp-jshint/gulp-tslint
I would like to push a PR to achieve compatibility with `gulp-reporter`

![gulp-reporter demo](/gucong3000/gulp-reporter/raw/master/demo.gif)

**Comment by jedmao** [comment]
Sounds great. How are the pandas over there? 🐼
