### ISSUE TITLE
Cli command not found for 2.0.0 release

### ISSUE THREAD

**Issue by ismay** [jedmao/eclint#58]
When installing the new release (v2) the command isn't available in `node_modules/.bin`. Version 1.1.5 worked fine for me. It seems that the new release isn't linking the cli command to `.bin`?

See here for the failing build: https://travis-ci.org/ismay/ismaywolff.nl/builds/213686565#L467

Ref: https://github.com/ismay/ismaywolff.nl/pull/240

**Comment by jedmao** [comment]
Published as v2.0.1.

**Comment by ismay** [comment]
That fixed it: https://travis-ci.org/ismay/ismaywolff.nl/builds/213827883#L415, thanks for the quick fix!
