### ISSUE TITLE
.eclintignore?

### ISSUE THREAD

**Issue by jonathanong** [jedmao/eclint#80]
i would like to do `eclint fix .` and use a `.eclintignore` to ignore node modules, etc. this is similar to how i use eslint.

**Comment by jedmao** [comment]
The only way to ignore things with `.editorconfig` is like this:
```ini
root = true

[*]
indent_size = 4

[*.md]
indent_size = unset
````
In the example above, Markdown files would be "ignored" like you were hoping.

**Comment by jonathanong** [comment]
no, i am asking to ignore files checked by this tool. for example, i don't want to check `node_modules`

**Comment by jedmao** [comment]
Duplicate of #47

**Comment by gucong3000** [comment]
use command `eclint fix`, do not need `.`, and edit `.gitignore`. eclint will ignore files defined in here.

**Comment by silverwind** [comment]
There are examples for when you want to include files in git but want to exclude them from eclint.

I think this is best solved in Editorconfig as oppsed to introducing a separate ignore pattern configuration for eclint, e.g. https://github.com/editorconfig/editorconfig/issues/228.

**Comment by Kristinita** [comment]
> use command eclint fix, do not need ., and edit .gitignore. eclint will ignore files defined in here.

@gucong3000 , I think, it must be in README. Users can long search for how to ignore files.

Thanks.
