### ISSUE TITLE
Support directories on command line

### ISSUE THREAD

**Issue by silverwind** [jedmao/eclint#83]
It'd be neat if one could pass a directory and files inside would get enumerated. For example

```
├── dir
│   ├── file1.txt
│   ├── file2.txt
```

`eclint check dir` should check both files. Currently it does nothing in this case.

**Comment by gucong3000** [comment]
`eclint check dir/**/*`

**Comment by silverwind** [comment]
> eclint check dir/**/*

This won't work if the user has extended globbing disabled in their shell. Another issue with that expansion is that there's the issues that globs like this can easily reach the maximum shell command line length, which, depending on environment can be as short as 32000 characters.

**Comment by gucong3000** [comment]
`eclint check "dir/**/*"` or just `eclint fix`

**Comment by gucong3000** [comment]
Globs support by `vinyl-fs`

**Comment by silverwind** [comment]
Okay, so `eclint check 'dir/**/*'` should work without shell globbing. Still I think it'd be nice to support directories directly, eslint does support it too.

**Comment by gucong3000** [comment]
PR is welcome.
