### ISSUE TITLE
Support block comments defined only via start and end

### ISSUE THREAD

**Issue by silverwind** [jedmao/eclint#85]
For example, block comments in CSS:

````css
/* block
   comment */
````

This fails to pass with these options:

````ini
[*.css]
block_comment_start = /*
block_comment_end = */
````

Another issue with above block is that it fails the `indent_size` rule when it is set to 2 or 4, while I think it should be accepted. I'd suggest to disable `indent_size` checks inside block comments.

**Comment by gucong3000** [comment]
try `eclint fix **/*.css`

**Comment by gucong3000** [comment]
```css
/*
 * block
 * comment
 */
```
We only support c lang style block comment

**Comment by silverwind** [comment]
These extra `*` are purely stylistic and should be ignored when linting, they are not mandatory in C either.

**Comment by gucong3000** [comment]
If you want disable `indent_size` checks inside block comments, you can try [lintspaces](https://www.npmjs.com/package/lintspaces)

**Comment by gucong3000** [comment]
I will work for support this kind of commit (node just disable);
```css
/* block
   comment */
```

**Comment by gucong3000** [comment]
Whould you like to try this PR #87 and do some test?
you can install from `npm i jedmao/eclint#non_doc_block_comments`

**Comment by gucong3000** [comment]
@silverwind The new release destroys some pipeline of projects. I plan to not support for this format in `eclint.fix()`, just support it in `eclint.check()`.

#96

**Comment by gucong3000** [comment]
If you have any way to compatible all of these formats, please submit PRs

**Comment by silverwind** [comment]
Why not keep it simple and ignore indentation in block comments completely (both in `fix` and `check`)? You can't really guess what kind of comment style a user uses, unless EditorConfig has an option for it.

**Comment by gucong3000** [comment]
As far as I know, `eclint` is the only linter that supports comments. [lintspaces](https://github.com/schorfES/node-lintspaces) is compatible with `.editorconfig`, and it have a [option](https://github.com/schorfES/node-lintspaces#ignores-option) to ignore indentation in comments.
Does users need two tools with same features?

**Comment by gucong3000** [comment]
> Why not keep it simple and ignore indentation in block comments.

Because this feature worked well in each project I was involved in.

**Comment by gucong3000** [comment]
```js
/*
 * block
 * comment
 */
```
Do you hate this comment style? It is support by many IDE and editor.

**Comment by silverwind** [comment]
It might be a good idea to add/parse an option in `.editorconfig` for block comment indentation style.

**Comment by silverwind** [comment]
And no, I don't hate your style, but I see it as extra typing work that can be avoided. ;)

**Comment by gucong3000** [comment]
> It might be a good idea to add/parse an option

What is this options look like？

**Comment by silverwind** [comment]
I guess it could use names for the styles, like `indent_brace_style` does, but in the simple case, strings like `aligned` for your style, and any other value for ignoring indentation would be fine I guess. You could add support for more styles later. The option could be called `block_comment_indent_style`.

**Comment by gucong3000** [comment]
we should open a new issue for editorconfig/editorconfig

**Comment by gucong3000** [comment]
I think stylelint is mach better than eclint for CSS file

**Comment by silverwind** [comment]
Yeah, I actually use both :)
